name: Go checks
on: ["pull_request"]

jobs:
  go_coverage:
    name: Check Go Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14"

      - name: Install dependencies
        env:
          GO111MODULE: off
        run: |
          go mod download
          go get github.com/mattn/goveralls

      - name: Run tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Report coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $(go env GOPATH)/bin/goveralls -coverprofile=covprofile -service=github
